######################################################################
# Automatically generated by qmake (3.1) Sun Dec 27 13:25:22 2020
######################################################################

TEMPLATE = app
TARGET = DynamicTemplates
INCLUDEPATH += .

QT += widgets
QT += printsupport
QT += svg

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += MyWindow.h RenderArea.h
SOURCES += \
           main.cpp \
           MyWindow--createCalendarTab.cpp \
           MyWindow--createChartsTab.cpp \
           MyWindow--createChecklistsTab.cpp \
           MyWindow--createLinesTab.cpp \
           MyWindow--createNotesTab.cpp \
           MyWindow--createPageSizeTab.cpp \
           MyWindow--createTemplateTab.cpp \
           MyWindow.cpp \
           RenderArea.cpp \
           RenderArea/RenderArea--draw.cpp \
           RenderArea/RenderArea--drawAppointmentRow.cpp \
           RenderArea/RenderArea--drawBar.cpp \
           RenderArea/RenderArea--drawGradientBox.cpp \
           RenderArea/RenderArea--drawLittleMonth.cpp \
           RenderArea/RenderArea--drawOneShortDay.cpp \
           RenderArea/RenderArea--drawRow.cpp \
           RenderArea/RenderArea--drawShadowedRect.cpp \
           RenderArea/RenderArea--drawSubHeader.cpp \
           RenderArea/RenderArea--fitRectToString.cpp \
           RenderArea/RenderArea--fitStringInRect.cpp \
           RenderArea/RenderArea--sets.cpp \
           RenderArea/notes/drawSinglePageNotes.cpp \
           RenderArea/calendars/onePagePerDay/onePagePerDayDrawPage.cpp \
           RenderArea/calendars/onePagePerMonth/onePagePerMonthDrawPage.cpp \
           RenderArea/calendars/onePagePerWeek/onePagePerWeekDrawPage.cpp \
           RenderArea/calendars/onePagePerYear/onePagePerTwoYearsDrawPage.cpp \
           RenderArea/calendars/onePagePerYear/onePagePerYearDrawPage.cpp \
           RenderArea/calendars/twoPagePerDay/twoPagePerDayDrawDay.cpp \
           RenderArea/calendars/twoPagePerDay/twoPagePerDayDrawOtherPage.cpp \
           RenderArea/calendars/twoPagePerMonth/twoPagePerMonthDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerMonth/twoPagePerMonthDrawPage.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekDrawPage.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekMoleskineStyleDrawPage.cpp \
           RenderArea/calendars/twoPagePerYear/twoPagePerYearDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerYear/twoPagePerYearDrawPage.cpp
